"""Add conversation kind, separating chat from scheduled tasks

Revision ID: 73fc43c5f170
Revises: 4429fd81b9be
Create Date: 2026-08-14 22:34:58.285965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fc43c5f170'
down_revision: Union[str, Sequence[str], None] = '4429fd81b9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is required, not optional. Adding a NOT NULL column to a
    # table that already has rows fails without one -- there would be no
    # value to put in the existing rows. Autogenerate cannot know what that
    # value should be, which is what its "please adjust!" refers to.
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "kind",
                sa.String(length=20),
                nullable=False,
                server_default="chat",
            )
        )

    # Backfill. Every existing conversation has just been marked "chat",
    # including the ones scheduled tasks created for themselves -- which is
    # the bug this migration exists to fix. Their title is the only signal
    # available after the fact, and it is one this code wrote itself, so it
    # is reliable here in a way a general heuristic would not be.
    op.execute(
        "UPDATE conversations SET kind = 'task' WHERE title LIKE 'Scheduled: %'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
